name: plant-waterer
version: '3.8'

services:
  frontend:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"

  api:
    build:
      context: ./src/api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"