name: plant-waterer
version: '3.8'

services:

  database:
    container_name: database
    image: postgres:17.6-alpine3.22
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: plant_waterer
      PGDATA: /database
    volumes:
      - ./src/database/storage:/database
    ports:
      - "5432:5432"
    networks:
      - plant-network

  api:
    container_name: api
    build:
      context: ./src/api
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: plant_waterer
      POLLING_INTERVAL: 30 # seconds
    ports:
      - "8000:8000"
    networks:
      - plant-network
    depends_on:
      - database
        

  frontend:
    container_name: frontend
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
    environment:
      API_ENDPOINT: http://api:8000
    ports:
      - "80:3000"
    networks:
      - plant-network
    depends_on:
      - api

networks:
  plant-network:
    driver: bridge