name: plant-waterer
version: '3.8'

services:
  backend:
    container_name: backend
    build:
      context: ./src/backend
      dockerfile: Dockerfile
    environment:
      DATABASE_TYPE: sqlite
      DATABASE_LOCATION: /app/db
      POLLING_INTERVAL: 30 # seconds
    volumes:
      - ./src/database/storage:/app/db
    ports:
      - "8000:8000"
    networks:
      - plant-network

  frontend:
    container_name: frontend
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
    environment:
      API_ENDPOINT: http://backend:8000
    ports:
      - "80:3000"
    networks:
      - plant-network
    depends_on:
      - backend

networks:
  plant-network:
    driver: bridge