[project]
name = "backend"
version = "0.1.0"
description = "Python backend for Water.md"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "apscheduler>=3.11.2",
    "fastapi[standard]>=0.128.0",
    "pillow>=12.1.0",
    "pydantic>=2.12.5",
    "python-multipart>=0.0.22",
    "sqlmodel>=0.0.31",
]

[project.optional-dependencies]
pi = [
    "adafruit-circuitpython-ads1x15",
    "rpi-gpio",
]

[dependency-groups]
dev = [
    "pytest>=9.0.2",
    "testcontainers[postgres]>=4.14.0",
]
